//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Script/Input/VR.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VR : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VR()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VR"",
    ""maps"": [
        {
            ""name"": ""XRI_Head"",
            ""id"": ""8d2215a8-1531-45e2-96a6-35a829876d92"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""663b3e22-d015-4027-89c9-b23cb28ccc4f"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""bad7d85f-1cc1-47a7-bab7-aa1a8df23248"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""97175667-4149-4412-98ce-a14ee08e0ea1"",
                    ""path"": ""<XRHMD>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45d53291-08bf-45d9-a0de-9cf8036b9e3c"",
                    ""path"": ""<XRHMD>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""XRI_HandLeft"",
            ""id"": ""27ca2cd8-ff91-4bd0-9412-24c7886f038c"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""ad1b05cf-2dfb-4435-a459-9db825859b94"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""a7a6b487-f799-4a9a-8c8b-3ff3c5dd5a14"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Take"",
                    ""type"": ""Value"",
                    ""id"": ""f2c1b442-78fe-4cae-9680-2ed224951812"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TakeButton"",
                    ""type"": ""Button"",
                    ""id"": ""3530a0e6-afd4-4b05-b60c-cd325814a904"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""stick"",
                    ""type"": ""Value"",
                    ""id"": ""14bc644c-9153-4fe7-a604-19f4d05a209f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""97a7931a-f02f-4044-b832-35ffdbf6edb8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0d442a9a-4ef9-48c6-988b-3678b334284b"",
                    ""path"": ""<XRController>{LeftHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8e047aa-fe32-46a1-9b8f-d05ef9f41844"",
                    ""path"": ""<XRController>{LeftHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac41fbcf-f65c-4895-aaa7-1c6147e90664"",
                    ""path"": ""<OculusTouchController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3e27af2-1785-4bc2-982e-bf93a0718a44"",
                    ""path"": ""<XRSimulatedController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d84b46aa-4c65-45bb-93e2-d918359e69ea"",
                    ""path"": ""<XRSimulatedController>{LeftHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ac0f3af-4298-4463-ab88-49180b2bcdf4"",
                    ""path"": ""<OculusTouchController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daaafe6f-9b98-4a24-8fe8-34376ed559be"",
                    ""path"": ""<OculusTouchController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40d3f995-7791-4117-bf16-995fe59cc0ec"",
                    ""path"": ""<XRSimulatedController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cd627be-54ea-481c-8f19-dec73c69426f"",
                    ""path"": ""<XRSimulatedController>{LeftHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1acca575-e0c9-4366-94bd-5f429a966425"",
                    ""path"": ""<OculusTouchController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42e7c995-0794-4804-87d6-82e237c14ccb"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c25b8900-9bbf-4a8d-836c-adb929e9f86f"",
                    ""path"": ""<OculusTouchController>/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""XRI_HandRight"",
            ""id"": ""3ed9ba19-ada3-43a8-bbf4-c9555a409217"",
            ""actions"": [
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""b1c249f0-87a3-4a09-89fe-d4dddcb29ed7"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""e90bf5af-7642-4a7f-9750-0c7388974515"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Take"",
                    ""type"": ""Value"",
                    ""id"": ""8e583325-caef-4d24-a02b-ea1210e03f0d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TakeButton"",
                    ""type"": ""Button"",
                    ""id"": ""8651140d-6a2d-461c-bf2c-fb42d7e9daf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""stick"",
                    ""type"": ""Value"",
                    ""id"": ""7f667e5f-6d32-4d63-8d80-eeed1688bc74"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""14a634c1-ca50-4f88-93ad-a286ba7b29ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""35bdf8ef-3f8c-4506-b3a4-feb573a68345"",
                    ""path"": ""<XRController>{RightHand}/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc962ac5-678f-4ba4-90c2-1a7bfc981262"",
                    ""path"": ""<XRController>{RightHand}/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa8add2e-01b2-4899-b7e5-5a2e35425ae5"",
                    ""path"": ""<XRSimulatedController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd7e5d14-dac8-4972-af5b-7814ee7778a8"",
                    ""path"": ""<OculusTouchController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7439f82-6f7a-43e7-b3a6-099c70a7ab00"",
                    ""path"": ""<XRSimulatedController>{RightHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cefeac76-0407-4240-97b2-699726d0ea58"",
                    ""path"": ""<OculusTouchController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Take"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f84663b-75ca-48bf-8f5f-2897c8cb6bac"",
                    ""path"": ""<XRSimulatedController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5d8086a-a20c-443f-9674-8483fdc9f743"",
                    ""path"": ""<OculusTouchController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a31d922a-4a87-4189-9eee-42ededda88c2"",
                    ""path"": ""<XRSimulatedController>{RightHand}/triggerButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b36a8b8-c0a5-4741-ac3a-aeb05c0e9a6d"",
                    ""path"": ""<OculusTouchController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""faed78d0-0309-4c97-8d00-028f6c8f78cb"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1141ee64-6710-4226-a7aa-41ce97903928"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // XRI_Head
        m_XRI_Head = asset.FindActionMap("XRI_Head", throwIfNotFound: true);
        m_XRI_Head_Position = m_XRI_Head.FindAction("Position", throwIfNotFound: true);
        m_XRI_Head_Rotation = m_XRI_Head.FindAction("Rotation", throwIfNotFound: true);
        // XRI_HandLeft
        m_XRI_HandLeft = asset.FindActionMap("XRI_HandLeft", throwIfNotFound: true);
        m_XRI_HandLeft_Position = m_XRI_HandLeft.FindAction("Position", throwIfNotFound: true);
        m_XRI_HandLeft_Rotation = m_XRI_HandLeft.FindAction("Rotation", throwIfNotFound: true);
        m_XRI_HandLeft_Take = m_XRI_HandLeft.FindAction("Take", throwIfNotFound: true);
        m_XRI_HandLeft_TakeButton = m_XRI_HandLeft.FindAction("TakeButton", throwIfNotFound: true);
        m_XRI_HandLeft_stick = m_XRI_HandLeft.FindAction("stick", throwIfNotFound: true);
        m_XRI_HandLeft_Accept = m_XRI_HandLeft.FindAction("Accept", throwIfNotFound: true);
        // XRI_HandRight
        m_XRI_HandRight = asset.FindActionMap("XRI_HandRight", throwIfNotFound: true);
        m_XRI_HandRight_Position = m_XRI_HandRight.FindAction("Position", throwIfNotFound: true);
        m_XRI_HandRight_Rotation = m_XRI_HandRight.FindAction("Rotation", throwIfNotFound: true);
        m_XRI_HandRight_Take = m_XRI_HandRight.FindAction("Take", throwIfNotFound: true);
        m_XRI_HandRight_TakeButton = m_XRI_HandRight.FindAction("TakeButton", throwIfNotFound: true);
        m_XRI_HandRight_stick = m_XRI_HandRight.FindAction("stick", throwIfNotFound: true);
        m_XRI_HandRight_Accept = m_XRI_HandRight.FindAction("Accept", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // XRI_Head
    private readonly InputActionMap m_XRI_Head;
    private IXRI_HeadActions m_XRI_HeadActionsCallbackInterface;
    private readonly InputAction m_XRI_Head_Position;
    private readonly InputAction m_XRI_Head_Rotation;
    public struct XRI_HeadActions
    {
        private @VR m_Wrapper;
        public XRI_HeadActions(@VR wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_XRI_Head_Position;
        public InputAction @Rotation => m_Wrapper.m_XRI_Head_Rotation;
        public InputActionMap Get() { return m_Wrapper.m_XRI_Head; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(XRI_HeadActions set) { return set.Get(); }
        public void SetCallbacks(IXRI_HeadActions instance)
        {
            if (m_Wrapper.m_XRI_HeadActionsCallbackInterface != null)
            {
                @Position.started -= m_Wrapper.m_XRI_HeadActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_XRI_HeadActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_XRI_HeadActionsCallbackInterface.OnPosition;
                @Rotation.started -= m_Wrapper.m_XRI_HeadActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_XRI_HeadActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_XRI_HeadActionsCallbackInterface.OnRotation;
            }
            m_Wrapper.m_XRI_HeadActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
            }
        }
    }
    public XRI_HeadActions @XRI_Head => new XRI_HeadActions(this);

    // XRI_HandLeft
    private readonly InputActionMap m_XRI_HandLeft;
    private IXRI_HandLeftActions m_XRI_HandLeftActionsCallbackInterface;
    private readonly InputAction m_XRI_HandLeft_Position;
    private readonly InputAction m_XRI_HandLeft_Rotation;
    private readonly InputAction m_XRI_HandLeft_Take;
    private readonly InputAction m_XRI_HandLeft_TakeButton;
    private readonly InputAction m_XRI_HandLeft_stick;
    private readonly InputAction m_XRI_HandLeft_Accept;
    public struct XRI_HandLeftActions
    {
        private @VR m_Wrapper;
        public XRI_HandLeftActions(@VR wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_XRI_HandLeft_Position;
        public InputAction @Rotation => m_Wrapper.m_XRI_HandLeft_Rotation;
        public InputAction @Take => m_Wrapper.m_XRI_HandLeft_Take;
        public InputAction @TakeButton => m_Wrapper.m_XRI_HandLeft_TakeButton;
        public InputAction @stick => m_Wrapper.m_XRI_HandLeft_stick;
        public InputAction @Accept => m_Wrapper.m_XRI_HandLeft_Accept;
        public InputActionMap Get() { return m_Wrapper.m_XRI_HandLeft; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(XRI_HandLeftActions set) { return set.Get(); }
        public void SetCallbacks(IXRI_HandLeftActions instance)
        {
            if (m_Wrapper.m_XRI_HandLeftActionsCallbackInterface != null)
            {
                @Position.started -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnPosition;
                @Rotation.started -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnRotation;
                @Take.started -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnTake;
                @Take.performed -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnTake;
                @Take.canceled -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnTake;
                @TakeButton.started -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnTakeButton;
                @TakeButton.performed -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnTakeButton;
                @TakeButton.canceled -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnTakeButton;
                @stick.started -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnStick;
                @stick.performed -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnStick;
                @stick.canceled -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnStick;
                @Accept.started -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnAccept;
                @Accept.performed -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnAccept;
                @Accept.canceled -= m_Wrapper.m_XRI_HandLeftActionsCallbackInterface.OnAccept;
            }
            m_Wrapper.m_XRI_HandLeftActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @Take.started += instance.OnTake;
                @Take.performed += instance.OnTake;
                @Take.canceled += instance.OnTake;
                @TakeButton.started += instance.OnTakeButton;
                @TakeButton.performed += instance.OnTakeButton;
                @TakeButton.canceled += instance.OnTakeButton;
                @stick.started += instance.OnStick;
                @stick.performed += instance.OnStick;
                @stick.canceled += instance.OnStick;
                @Accept.started += instance.OnAccept;
                @Accept.performed += instance.OnAccept;
                @Accept.canceled += instance.OnAccept;
            }
        }
    }
    public XRI_HandLeftActions @XRI_HandLeft => new XRI_HandLeftActions(this);

    // XRI_HandRight
    private readonly InputActionMap m_XRI_HandRight;
    private IXRI_HandRightActions m_XRI_HandRightActionsCallbackInterface;
    private readonly InputAction m_XRI_HandRight_Position;
    private readonly InputAction m_XRI_HandRight_Rotation;
    private readonly InputAction m_XRI_HandRight_Take;
    private readonly InputAction m_XRI_HandRight_TakeButton;
    private readonly InputAction m_XRI_HandRight_stick;
    private readonly InputAction m_XRI_HandRight_Accept;
    public struct XRI_HandRightActions
    {
        private @VR m_Wrapper;
        public XRI_HandRightActions(@VR wrapper) { m_Wrapper = wrapper; }
        public InputAction @Position => m_Wrapper.m_XRI_HandRight_Position;
        public InputAction @Rotation => m_Wrapper.m_XRI_HandRight_Rotation;
        public InputAction @Take => m_Wrapper.m_XRI_HandRight_Take;
        public InputAction @TakeButton => m_Wrapper.m_XRI_HandRight_TakeButton;
        public InputAction @stick => m_Wrapper.m_XRI_HandRight_stick;
        public InputAction @Accept => m_Wrapper.m_XRI_HandRight_Accept;
        public InputActionMap Get() { return m_Wrapper.m_XRI_HandRight; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(XRI_HandRightActions set) { return set.Get(); }
        public void SetCallbacks(IXRI_HandRightActions instance)
        {
            if (m_Wrapper.m_XRI_HandRightActionsCallbackInterface != null)
            {
                @Position.started -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnPosition;
                @Rotation.started -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnRotation;
                @Take.started -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnTake;
                @Take.performed -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnTake;
                @Take.canceled -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnTake;
                @TakeButton.started -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnTakeButton;
                @TakeButton.performed -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnTakeButton;
                @TakeButton.canceled -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnTakeButton;
                @stick.started -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnStick;
                @stick.performed -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnStick;
                @stick.canceled -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnStick;
                @Accept.started -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnAccept;
                @Accept.performed -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnAccept;
                @Accept.canceled -= m_Wrapper.m_XRI_HandRightActionsCallbackInterface.OnAccept;
            }
            m_Wrapper.m_XRI_HandRightActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @Take.started += instance.OnTake;
                @Take.performed += instance.OnTake;
                @Take.canceled += instance.OnTake;
                @TakeButton.started += instance.OnTakeButton;
                @TakeButton.performed += instance.OnTakeButton;
                @TakeButton.canceled += instance.OnTakeButton;
                @stick.started += instance.OnStick;
                @stick.performed += instance.OnStick;
                @stick.canceled += instance.OnStick;
                @Accept.started += instance.OnAccept;
                @Accept.performed += instance.OnAccept;
                @Accept.canceled += instance.OnAccept;
            }
        }
    }
    public XRI_HandRightActions @XRI_HandRight => new XRI_HandRightActions(this);
    public interface IXRI_HeadActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
    }
    public interface IXRI_HandLeftActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnTake(InputAction.CallbackContext context);
        void OnTakeButton(InputAction.CallbackContext context);
        void OnStick(InputAction.CallbackContext context);
        void OnAccept(InputAction.CallbackContext context);
    }
    public interface IXRI_HandRightActions
    {
        void OnPosition(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnTake(InputAction.CallbackContext context);
        void OnTakeButton(InputAction.CallbackContext context);
        void OnStick(InputAction.CallbackContext context);
        void OnAccept(InputAction.CallbackContext context);
    }
}
